## 1 导入必需的包

In [3]:
import tensorflow as tf
import time

In [68]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

In [69]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [70]:
start = time.time()

model.fit(x_train, y_train, epochs=5)

end = time.time()

model.evaluate(x_test, y_test)
print(end - start)

Epoch 1/5
1875/1875 [==============================] - 1s 382us/step - loss: 0.5066 - accuracy: 0.8480
Epoch 2/5
1875/1875 [==============================] - 1s 385us/step - loss: 0.1957 - accuracy: 0.94170s - loss: 0.2
Epoch 3/5
1875/1875 [==============================] - 1s 376us/step - loss: 0.1538 - accuracy: 0.9534
Epoch 4/5
1875/1875 [==============================] - 1s 376us/step - loss: 0.1339 - accuracy: 0.9596
Epoch 5/5
313/313 [==============================] - 0s 288us/step - loss: 0.0873 - accuracy: 0.9732
3.8132920265197754


## 2 创建张量tensor 
### tf.constant(value,shape=()或者[],dtype=tf.int32)
### dtype默认32位，numpy创建array默认64位，用array创建tensor也是64位

In [39]:
import numpy as np
a = np.arange(12).reshape((3,4))

In [40]:
t_a = tf.constant(a,shape=[4,3],dtype=tf.int32)
t_a

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [41]:
t_e = tf.constant(a,shape=[4,3],dtype=tf.int32)
t_e

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

### 转换tensor数据格式，tf,cast()

In [42]:
t_b = tf.cast(t_a,dtype=tf.float32)
t_b

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [43]:
t_c = tf.constant([1,2,3,4,5])
t_c

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [44]:
t_d = tf.fill(dims=(2,3),value=3)
t_d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [45]:
a = tf.random.normal((3,4),0,1)
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.07650166,  0.4378998 , -0.623822  ,  0.66472185],
       [-0.02749141, -0.49048364, -2.8141198 ,  0.24684855],
       [ 0.86789376, -0.45548534,  1.0619588 , -0.8789416 ]],
      dtype=float32)>

In [46]:
x1 = tf.range(10)
x2 = tf.range(10,0,-1)
x1,x2

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1], dtype=int32)>)

In [47]:
a = tf.range(24)
print(a)
print(tf.reshape(a,[2,3,4]))

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [48]:
a.ndim

1

In [49]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [50]:
tf.config.list_physical_devices('GPU')

[]

## 3 图像处理

In [51]:
from PIL import Image

ModuleNotFoundError: No module named 'PIL'

In [ ]:
img = Image.open("/Users/wangyizhang/Documents/JupyterNotebook/练习/IMG_1537.JPG")

In [ ]:
img.format

In [ ]:
img.size

In [ ]:
import numpy as np
img_arr = np.array(img)
img_arr

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(img)
plt.show()

In [ ]:
img_reverse = 255 - img_arr
plt.imshow(img_reverse)
plt.show()

In [ ]:
img_small = img.resize((2048,1500))
plt.imshow(img_small)
plt.show()

In [ ]:
img_small.save("/Users/wangyizhang/Documents/JupyterNotebook/练习/IMG_1538.JPG")

## 4 minist数据集

In [52]:
mnist = tf.keras.datasets.mnist
(train_x,train_y),(test_x,test_y) = mnist.load_data()

In [53]:
train_x.shape

(60000, 28, 28)

In [54]:
train_x.dtype

dtype('uint8')

In [55]:
import matplotlib.pyplot as plt
plt.imshow(train_x[0])
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

## 5 一元线性回归-python实现

In [56]:
import numpy as np

x = list(range(100))
y = [i*3+6 for i in range(100)]

In [57]:
x_m = np.mean(x); y_m = np.mean(y)
lxy = 0; lxx = 0

for i in range(len(x)):
    lxy += (x[i] - x_m) * (y[i] - y_m)
    lxx += (x[i] - x_m) ** 2

w = lxy/lxx
b = y_m - w * x_m

In [58]:
w,b

(3.0, 6.0)

In [59]:
x_p = [13,4,65,29,30,31,87,143,49,76,99]
y_p = [w*j+b for j in x_p]
y_p

[45.0, 18.0, 201.0, 93.0, 96.0, 99.0, 267.0, 435.0, 153.0, 234.0, 303.0]

### tensorflow实现

In [60]:
import tensorflow as tf

x_t = tf.constant(x,dtype=tf.float32)
y_t = tf.constant(y,dtype=tf.float32)

In [65]:
x_t_m = tf.reduce_mean(x_t)
y_t_m = tf.reduce_mean(y_t)
x_t_m, y_t_m

(<tf.Tensor: shape=(), dtype=float32, numpy=49.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=154.5>)

In [62]:
lxy = tf.reduce_sum((x_t - x_t_m) * (y_t - y_t_m))
lxx = tf.reduce_sum((x_t - x_t_m) ** 2)

In [66]:
w = lxy/lxx
b = y_t_m - w * x_t_m
w, b

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [64]:
x_p_t = tf.constant(x_p,dtype=tf.float32)
y_p_t = w * x_p_t + b
y_p_t

<tf.Tensor: shape=(11,), dtype=float32, numpy=
array([ 45.,  18., 201.,  93.,  96.,  99., 267., 435., 153., 234., 303.],
      dtype=float32)>

## 6 Tensorflow自动求导机制

In [41]:
import tensorflow as tf
import numpy as np
# import matplotlib.pyplot as plt
tf.__version__

'2.4.0-rc0'

### 创建Variable变量，可由数字、list、ndarray、tensor创建

In [10]:
num_v = tf.Variable(3)
num_v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [11]:
lis_v = tf.Variable([1,3,5,7,9])
lis_v

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [12]:
arr_v = tf.Variable(np.array(range(12)).reshape(3,4))
arr_v

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int64, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [38]:
ten_v = tf.Variable(tf.constant(np.array(np.arange(12)).reshape(2,2,3)))
ten_v

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [15]:
num_v.trainable,lis_v.trainable,arr_v.trainable,ten_v.trainable

(True, True, True, True)

In [16]:
ten_v.shape,ten_v.dtype

(TensorShape([2, 2, 3]), tf.int64)

In [17]:
arr_v.shape,arr_v.dtype

(TensorShape([3, 4]), tf.int64)

In [18]:
type(arr_v),type(ten_v)

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 tensorflow.python.ops.resource_variable_ops.ResourceVariable)

In [40]:
# 判断类型 isinstance()
isinstance(ten_v,tf.Tensor),isinstance(ten_v,tf.Variable)

(False, True)

### 自动求导-GradientTape

In [24]:
x = tf.Variable(3.)

with tf.GradientTape() as tape:
    y = tf.square(x)
    z = pow(x,3)
    
dy_dx = tape.gradient(y,x)
dz_dx = tape.gradient(z,x)

RuntimeError: A non-persistent GradientTape can only be used tocompute one set of gradients (or jacobians)

In [21]:
y,dy_dx

(<tf.Tensor: shape=(), dtype=float32, numpy=9.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [23]:
type(x),type(y)

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 tensorflow.python.framework.ops.EagerTensor)

### TensorFlow实现一元线性回归


In [64]:
x = tf.constant(np.random.normal(50))
y = tf.constant(np.random.normal(50))

In [65]:
w = tf.Variable(np.random.randn())
b = tf.Variable(np.random.randn())

In [68]:
for i in range(50):
    with tf.GradientTape(persistent=True) as tape:
        pred = w * x + b
        loss = 0.5*tf.reduce_mean(tf.square(y-pred))
    dl_dw = tape.gradient(loss,w)
    dl_db = tape.gradient(loss,b)
    
    w.assign_sub(learning_rate*dl_dw)
    b.assign_sub(learning_rate*dl_db)

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Mul]

In [67]:
for i in range(50):
    with tf.GradientTape() as tape:
        pred = w * x + b
        loss = 0.5*tf.reduce_mean(tf.square(y-pred))
    dl_dw,dl_db = tape.gradient(loss,[w,b])
    
    w.assign_sub(learning_rate*dl_dw)
    b.assign_sub(learning_rate*dl_db)

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Mul]

In [59]:
p = w * x + b
p

<tf.Tensor: shape=(), dtype=float32, numpy=48.99314>

## TensorFlow实现人工神经网络

In [4]:
import tensorflow as tf
tf.__version__

'2.4.0-rc0'

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

### 创建模型

In [8]:
model = tf.keras.Sequential()
model

In [10]:
model.add(tf.keras.layers.Dense(8,activation='relu',input_shape=(4,)))
model.add(tf.keras.layers.Dense(4,activation='relu'))
model.add(tf.keras.layers.Dense(3,activation='softmax'))

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 91
Trainable params: 91
Non-trainable params: 0
_________________________________________________________________


### 编译模型
#### model.compile(loss,optimizer,metrics)

In [12]:
model.compile(loss='mse',optimizer='adam',metrics='accuracy')

### 训练模型
#### model.fit()

In [ ]:
model.fit(trainx,trainy,epochs=50,batch_size=200)

### Sequential 实现手写数字识别

In [1]:
import tensorflow as tf
import numpy as np

#### 加载数据

In [2]:
mnist = tf.keras.datasets.mnist
(train_x,train_y),(test_x,test_y) = mnist.load_data()

In [3]:
train_x.shape, train_y.shape, test_x.shape, test_y.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [4]:
type(train_x)

numpy.ndarray

#### 数据预处理

In [5]:
X_train, X_test = tf.cast(train_x/255.,tf.float32), tf.cast(test_x/255.,tf.float32)
y_train, y_test = tf.cast(train_y,tf.int16), tf.cast(test_y,tf.int16)

In [6]:
type(X_train), type(y_train)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

#### 创建模型

In [19]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


#### 编译模型

In [20]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics='sparse_categorical_accuracy')

#### 训练模型

In [21]:
model.fit(X_train,y_train,batch_size=50,epochs=5,validation_split=0.2)

Epoch 1/5
960/960 [==============================] - 1s 539us/step - loss: 0.5139 - sparse_categorical_accuracy: 0.8532 - val_loss: 0.1797 - val_sparse_categorical_accuracy: 0.9486
Epoch 2/5
960/960 [==============================] - 0s 459us/step - loss: 0.1582 - sparse_categorical_accuracy: 0.9549 - val_loss: 0.1321 - val_sparse_categorical_accuracy: 0.9619
Epoch 3/5
960/960 [==============================] - 0s 468us/step - loss: 0.0993 - sparse_categorical_accuracy: 0.9729 - val_loss: 0.1031 - val_sparse_categorical_accuracy: 0.9692
Epoch 4/5
960/960 [==============================] - 0s 475us/step - loss: 0.0733 - sparse_categorical_accuracy: 0.9791 - val_loss: 0.0984 - val_sparse_categorical_accuracy: 0.9716
Epoch 5/5
960/960 [==============================] - 0s 464us/step - loss: 0.0530 - sparse_categorical_accuracy: 0.9851 - val_loss: 0.0881 - val_sparse_categorical_accuracy: 0.9742


#### 测试模型

In [22]:
model.evaluate(X_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0866 - sparse_categorical_accuracy: 0.1006


[0.08658363670110703, 0.1005999967455864]

#### 使用模型

In [23]:
y_pred = np.argmax(model.predict([[X_train[0]]]))
y_pred

ValueError: in user code:

    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1478 predict_function  *
        return step_function(self, iterator)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1461 run_step  **
        outputs = model.predict_step(data)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1434 predict_step
        return self(x, training=False)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1007 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:375 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:424 call
        return self._run_internal_graph(
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:560 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:993 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/wangyizhang/tensorflow_macos_venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:255 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer dense_3 is incompatible with the layer: expected axis -1 of input shape to have value 784 but received input with shape (None, 28)


#### 保存与加载模型

In [25]:
# 保存模型（仅保存模型参数）
model.save_weights('mnist_weights.h5')

In [26]:
# 加载模型
# 无需训练，仍需创建、配置模型
model.load_weights('mnist_weights.h5')

In [27]:
# 保存整个模型（保存模型结构、参数、配置、优化器状态）
model.save_weights('mnist_weights_all.h5')

In [7]:
# 加载模型
# 无需创建、配置、训练模型
model = tf.keras.models.load_model('mnist_weights_all.h5')

ValueError: No model found in config file.